"""Write Harmony JSON, Julia case data, and a PSCAD geometry note from line_cases.py."""
from __future__ import annotations

from pathlib import Path

from line_cases import (
    CABLE_CASES,
    CABLE_LAYERS,
    FREQ,
    OHL_CASES,
    _geo_array,
    all_line_ids,
    ohl_geometry_row,
    ohl_params,
)

ROOT = Path(__file__).resolve().parent
HARMONY = ROOT / "harmony"


def _buses_for(prefix: str, n_pins: int):
    loc = "DC1" if prefix.startswith("cable") else "AC1"
    return [
        {"id": f"{prefix}_a", "location": loc, "pins": n_pins, "enabled": True},
        {"id": f"{prefix}_b", "location": loc, "pins": n_pins, "enabled": True},
    ]


def _ohl_component(case: dict) -> dict:
    e = ohl_params(case)
    gw = {"count": case.get("ng", 2)}
    if gw["count"] > 0:
        g = e["gw"]
        gw["geometry"] = [g["Rgdc"], g["rg"], g["dgsag"], g["dyg"], g["dxg"]]
        gw["mu_g"] = 1.0
    return {
        "id": case["id"],
        "location": "AC1",
        "type": "overhead_line",
        "length": e["length_m"],
        "earth": list(e["earth"]),
        "conductor": {
            "organization": case["org"],
            "number_bundles": [case["nb"], case["nsb"]],
            "geometry": _geo_array(case["org"], case["nb"], e),
            "rc": e["rc"],
            "Rdc": e["Rdc"],
            "dsag": e["dsag"],
            "dsb": case.get("dsb", 0.0),
        },
        "groundwire": gw,
        "connected_buses": [
            {"bus_id": f"{case['id']}_a", "terminal": 1},
            {"bus_id": f"{case['id']}_b", "terminal": 2},
        ],
        "enabled": True,
    }


def _cable_component(case: dict) -> dict:
    n = len(case["positions"])
    return {
        "id": case["id"],
        "location": "DC1",
        "type": "cable",
        "cable_type": case["cable_type"],
        "length": CABLE_LAYERS["length_m"],
        "earth": list(CABLE_LAYERS["earth"]),
        "pins": n,
        "conductors": CABLE_LAYERS["conductors"],
        "insulators": CABLE_LAYERS["insulators"],
        "positions": [list(p) for p in case["positions"]],
        "connected_buses": [
            {"bus_id": f"{case['id']}_a", "terminal": 1},
            {"bus_id": f"{case['id']}_b", "terminal": 2},
        ],
        "enabled": True,
    }


def write_harmony_json() -> Path:
    buses = []
    components = []
    computations = []
    for case in OHL_CASES:
        buses.extend(_buses_for(case["id"], case["nb"]))
        components.append(_ohl_component(case))
        computations.append(
            {
                "type": "y_matrix",
                "component_id": case["id"],
                "frequency_range": FREQ,
                "plot": False,
            }
        )
    for case in CABLE_CASES:
        buses.extend(_buses_for(case["id"], len(case["positions"])))
        components.append(_cable_component(case))
        computations.append(
            {
                "type": "y_matrix",
                "component_id": case["id"],
                "frequency_range": FREQ,
                "plot": False,
            }
        )
    doc = {
        "simulation": {
            "title": "line_topologies",
            "description": "All Harmony OHL organizations and coaxial cable layouts vs PowerImpedance.",
            "output_directory": "./files",
            "frequency_range": FREQ,
        },
        "buses": buses,
        "components": components,
        "computations": computations,
    }
    path = HARMONY / "line_topologies.json"
    import json

    path.write_text(json.dumps(doc, indent=4) + "\n", encoding="utf-8")
    return path


def _jl_tuple_pair(p):
    return f"({p[0]}, {p[1]})"


def write_julia_cases() -> Path:
    lines = [
        "# Auto-generated by build_line_cases.py. Do not edit by hand.",
        "const GEN_FREQ_START = 10.0",
        "const GEN_FREQ_STOP = 1000.0",
        "const GEN_FREQ_N = 21",
        "const GEN_OHL = [",
    ]
    for case in OHL_CASES:
        e = ohl_params(case)
        ng = case.get("ng", 2)
        g = e["gw"]
        lines.append(
            "    ("
            f'id="{case["id"]}", organization=:{case["org"]}, '
            f"nb={case['nb']}, nsb={case['nsb']}, "
            f"Rdc={e['Rdc']}, rc={e['rc']}, ybc={e['ybc']}, dy={e['dy']}, "
            f"dx={e['dx']}, dxt={e['dxt']}, dsb={case.get('dsb', 0.0)}, "
            f"dsag={e['dsag']}, ng={ng}, Rgdc={g['Rgdc']}, rg={g['rg']}, "
            f"dxg={g['dxg']}, dyg={g['dyg']}, dgsag={g['dgsag']}, "
            f"length={e['length_m']}, earth={e['earth']},"
            "),"
        )
    lines.append("]")
    lines.append("const GEN_CABLE = [")
    for case in CABLE_CASES:
        pos = ", ".join(_jl_tuple_pair(p) for p in case["positions"])
        lines.append(
            "    ("
            f'id="{case["id"]}", cable_type=:{case["cable_type"]}, '
            f"length={CABLE_LAYERS['length_m']}, earth={CABLE_LAYERS['earth']}, "
            f"positions=[{pos}],"
            "),"
        )
    lines.append("]")
    path = ROOT / "generated_line_cases.jl"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_geometry_md() -> Path:
    rows = [ohl_geometry_row(c) for c in OHL_CASES]
    lines = [
        "# OHL and cable geometry vs PSCAD Line Constants",
        "",
        "Harmony and PowerImpedance share the same named-organization formulas.",
        "PSCAD stock towers (3H / 3V / 3D, Universal Tower) use the conventions",
        "in the [overhead line tower](https://www.pscad.com/webhelp/Master_Library_Models/Transmission_Lines_Cables/Transmission_Line_Models/tower_comp.htm)",
        "and [earth-return](https://www.pscad.com/webhelp-v502-ol/EMTDC/Transmission_Lines/Mutual_Impedance_with_Earth_Return.htm) pages.",
        "",
        "Shared with PSCAD (not a discrepancy):",
        "",
        "- DC resistance is **Ω/km** (PSCAD “entire conductor”). Harmony multiplies by `1e-3`.",
        "- Sag: mean height `H − (2/3) sag` (PSCAD sag = tower height − mid-span).",
        "- Symmetrical bundle: ring of radius `d/(2 sin(π/n_sb))`, even-n rotated by `π/n_sb`.",
        "- Aerial earth return: Deri–Semlyen complex image (PSCAD default for overhead).",
        "- Cable earth return: Wedepohl–Wilcox (PSCAD default for coaxial SC cables).",
        "- Cable `ε0`: Harmony `8.854e-12` (SI). PowerImpedance uses `8.85e-12`.",
        "",
        "## OHL phase centres (before sag), metres",
        "",
        "| id | org | n | max |H−PSCAD| (m) | Harmony centres | PSCAD centres | Verdict |",
        "|----|-----|---|----------------:|-----------------|---------------|---------|",
    ]
    for r in rows:
        h = "; ".join(f"({x:.3f},{y:.3f})" for x, y in r["harmony_centres"])
        p = "; ".join(f"({x:.3f},{y:.3f})" for x, y in r["pscad_centres"])
        verd = "match" if r["pscad_match"] else "H=PI, not PSCAD"
        lines.append(
            f"| `{r['id']}` | {r['org']} | {r['nb']} | {r['centre_max_m']:.3f} | `{h}` | `{p}` | {verd} |"
        )
    lines.extend(
        [
            "",
            "## Notes per layout",
            "",
        ]
    )
    for r in rows:
        lines.append(f"- **{r['id']}**: {r['note']}")
    lines.extend(
        [
            "",
            "## Cable",
            "",
            "- Layers are the P2P coaxial stack (core / sheath / armour).",
            "- Kron reduction of sheath/armour is the default in both codes.",
            "- Equal-depth bipolar: self earth-return terms agree.",
            "- Staggered depths: Harmony uses per-cable $H=2 y_i$; PowerImpedance",
            "  copies the first cable’s self earth return onto every core.",
            "- Semiconductor screens (`a`,`b` ≠ 0) are not in this sweep.",
            "",
        ]
    )
    path = ROOT / "geometry.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def harmony_csv_names() -> list[str]:
    return [f"{i}.csv" for i in all_line_ids()]


def main() -> None:
    HARMONY.mkdir(parents=True, exist_ok=True)
    json_path = write_harmony_json()
    jl_path = write_julia_cases()
    md_path = write_geometry_md()
    print("wrote", json_path)
    print("wrote", jl_path)
    print("wrote", md_path)
    print("harmony csvs:", ", ".join(harmony_csv_names()))


if __name__ == "__main__":
    main()
