# Optional compiler cache (ccache / sccache).
if(DEFINED ENV{CCACHE_PROGRAM})
    set(CCACHE_PROGRAM "$ENV{CCACHE_PROGRAM}")
else()
    find_program(CCACHE_PROGRAM ccache)
    if(NOT CCACHE_PROGRAM)
        find_program(CCACHE_PROGRAM sccache)
    endif()
endif()

if(CCACHE_PROGRAM)
    set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
    set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
    message(STATUS "Compiler cache enabled: ${CCACHE_PROGRAM}")
endif()
