name: macOS examples

# Workflow triggers tell GitHub when to run the workflow:
on:
  # Allows workflow to be triggered manually from the GitHub UI (Actions tab)
  workflow_dispatch:
  # Runs at 2:00 AM UTC, Monday through Friday
  schedule:
    - cron: '0 2 * * 1-5'
  # When a pull request to merge a branch into main or develop is opened/updated
  pull_request:
    branches: [ "main", "develop"]

# This workflow defines one job: build-and-test
jobs:
  build-and-run-examples:
    
    # Use macos-latest runner.
    # See https://github.com/actions/runner-images for a list of available runners.
    runs-on: macos-latest
    
    steps:

      # Checkout a copy of this repository on the runner
      # We use the "checkout" GitHub Action
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # Install dependencies
      # Call .github/actions/setup-env/action.yml
      # This script creates the conda env and installs Gurobi and its license
      - name: Install dependencies
        uses: ./.github/actions/setup-env
        with:
          gurobi_wlsaccessid: ${{ secrets.GUROBI_WLSACCESSID }}
          gurobi_wlssecret: ${{ secrets.GUROBI_WLSSECRET }}
          gurobi_licenseid: ${{ secrets.GUROBI_LICENSEID }}

      # Build the tests
      - name: Build the tests
        shell: bash -l {0}
        run: |
          mkdir tests/build
          cd tests/build
          cmake .. -DGUROBI_PATH="/Library/gurobi1301/macos_universal2"
          cmake --build . --config Release -j4

      - name: Run the tests (examples only)
        uses: ./.github/actions/run-ctest
        with:
          gurobi_path: /Library/gurobi1301/macos_universal2
          ctest_args: '-R TestExamples'