name: macOS Build and Test

# Workflow triggers tell GitHub when to run the workflow:
on:
  # Allows workflow to be triggered manually from the GitHub UI (Actions tab)
  workflow_dispatch:
  # Runs at 2:00 AM UTC, Monday through Friday
  schedule:
    - cron: '0 2 * * 1-5'
  # When a pull request to merge a branch into main or develop is opened/updated
  pull_request:
    branches: [ "main", "develop"]

# This workflow defines one job: build-and-test
jobs:
  build-and-test:
    
    # Use macos-latest runner.
    # See https://github.com/actions/runner-images for a list of available runners.
    runs-on: macos-latest
    
    steps:

      # Checkout a copy of this repository on the runner
      # We use the "checkout" GitHub Action
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # Install conda on the runner
      # We use the "setup-miniconda" GitHub Action
      # https://github.com/marketplace/actions/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v3
        with:
            activate-environment: harmony
            auto-activate-base: false

      # Update conda environment with dependencies listed in environment.yml 
      - name: Create conda environment from environment.yml
        run: conda env update -n harmony -f environment.yml

      # Install Gurobi on the runner
      - name: Install Gurobi
        shell: bash -l {0}
        run: |
          mkdir dependencies
          cd dependencies
          curl -O https://packages.gurobi.com/13.0/gurobi13.0.1_macos_universal2.pkg
          sudo installer -pkg gurobi13.0.1_macos_universal2.pkg -target /

      # Setup the Gurobi WLS license
      # The actual license is stored as a repository secret
      - name: Setup Gurobi License
        run: |
          sudo mkdir -p /Library/gurobi
          sudo bash -c "cat <<EOF > /Library/gurobi/gurobi.lic
          WLSACCESSID=${{ secrets.GUROBI_WLSACCESSID }}
          WLSSECRET=${{ secrets.GUROBI_WLSSECRET }}
          LICENSEID=${{ secrets.GUROBI_LICENSEID }}
          EOF"

      # Build the tests
      - name: Build the tests
        shell: bash -l {0}
        run: |
          mkdir tests/build
          cd tests/build
          cmake .. -DGUROBI_PATH="/Library/gurobi1301/macos_universal2"
          cmake --build . --config Release -j4

      # Run the tests
      - name: Run the tests
        shell: bash -l {0}
        run: |
          cd tests/build
          ctest -j4 