name: Windows Build and Test

# Workflow triggers tell GitHub when to run the workflow:
# a) when there is a new commit on the main or develop branch
# b) when a new pull request is opened to merge a branch into main or develop
on:
  push:
    branches: [ "main", "develop", "github_actions"]
  pull_request:
    branches: [ "main", "develop"]

# This workflow defines one job: build-and-test
jobs:
  build-and-test:
    
    # Use windows-latest runner.
    # See https://github.com/actions/runner-images for a list of available runners.
    runs-on: windows-latest
    
    steps:

      # Checkout a copy of this repository on the runner
      # We use the "checkout" GitHub Action
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # Install conda on the runner
      # We use the "setup-miniconda" GitHub Action
      # https://github.com/marketplace/actions/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v3
        with:
            activate-environment: harmony
            auto-activate-base: false

      # Update conda environment with dependencies listed in environment.yml 
      - name: Create conda environment from environment.yml
        run: conda env update -n harmony -f environment.yml

      # Install Gurobi on the runner
      # Use msiexec to run the installer (/qn = quiet (no UI), /norestart = don't reboot the runner)
      - name: Install Gurobi
        run: |
          mkdir dependencies
          cd dependencies
          curl -LO https://packages.gurobi.com/13.0/Gurobi-13.0.1-win64.msi         
          Start-Process msiexec.exe -ArgumentList '/i', 'Gurobi-13.0.1-win64.msi', '/qn', '/norestart' -Wait -PassThru

      # Setup the Gurobi WLS license
      # The actual license is stored as a repository secret
      - name: Setup Gurobi License
        run: |
          if (!(Test-Path "C:\gurobi")) {
              New-Item -Path "C:\gurobi" -ItemType Directory -Force
          }

          $licenseContent = @"
          WLSACCESSID=${{ secrets.GUROBI_WLSACCESSID }}
          WLSSECRET=${{ secrets.GUROBI_WLSSECRET }}
          LICENSEID=${{ secrets.GUROBI_LICENSEID }}
          "@

          Set-Content -Path "C:\gurobi\gurobi.lic" -Value $licenseContent

      # Install Gnuplot on the runner
      # We use the choco package manager (equivalent of homebrew and apt)
      - name: Install Gnuplot
        run: |
          choco install gnuplot -y

      # Install Matplot++ on the runner
      # /S is the standard NSIS silent flag
      - name: Install Matplot++
        run: |
          cd dependencies
          ls
          curl -LO https://github.com/alandefreitas/matplotplusplus/releases/download/v1.2.0/Matplot++-1.2.0-win64.exe
          ./Matplot++-1.2.0-win64.exe /S
      
      # Build the tests
      - name: Build the tests
        shell: bash -l {0}
        run: |
          mkdir tests/build
          cd tests/build
          cmake .. -DGUROBI_PATH="C:\gurobi1301\win64" -DMATPLOT_PATH="C:\Program Files\Matplot++ 1.2.0"
          cmake --build . --config Release

      # Run the tests
      - name: Run the tests
        shell: bash -l {0}
        run: |
          export PATH="/c/gurobi1301/win64/bin:/c/Program Files/Matplot++ 1.2.0/lib:/c/Program Files/gnuplot/bin:$PATH"
          cd tests/build
          ctest

      # Configure CMake project and compile Harmony
      - name: Configure CMake and compile
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake .. -DGUROBI_PATH="C:\gurobi1301\win64" -DMATPLOT_PATH="C:\Program Files\Matplot++ 1.2.0"
          cmake --build . --config Release

      # Run Harmony
      - name: Run Tests
        shell: bash -l {0}
        run: |
          export PATH="/c/gurobi1301/win64/bin:/c/Program Files/Matplot++ 1.2.0/lib:/c/Program Files/gnuplot/bin:$PATH"
          cd build/Release
          ./Harmony.exe